[__config__]
oldver = "cur_ver.json"
newver = "new_ver.json"

[passwall]
source = "git"
git = "https://github.com/Openwrt-Passwall/openwrt-passwall"

[passwall2]
source = "git"
git = "https://github.com/Openwrt-Passwall/openwrt-passwall2"
