name: Test SDK Simple
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false
      - uses: actions/checkout@v7
      - uses: moetayuko/gh-action-sdk@main
        env:
          ARCH: x86_64-main
          V: s
