name: Test 4
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false
      - name: Build package
        uses: moetayuko/gh-action-sdk@main
        env:
          ARCH: x86_64-main
          EXTRA_FEEDS: >-
            src-git|passwall_packages|https://github.com/Openwrt-Passwall/openwrt-passwall-packages;main
            src-git|peditx_themes|https://github.com/peditx/luci-theme-peditx^main
          V: s
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: test-build
          path: bin/packages/x86_64/passwall*/*
          retention-days: 1
