name: Test Free Disk
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false
      - run: echo "Free disk done!"
